version: '3'
services:
    api:
        build: .
        environment: 
            - PYTHONUNBUFFERED=1
        ports:
            - "5000:5000"
        depends_on:
            - redis_db
    redis_db:
        image: "redis:alpine"
