version: '3'
services:
    api:
        build: .
        environment: 
            - PYTHONUNBUFFERED=1
            - MYSQL_USER=root
            - MYSQL_PASS=password
            - MYSQL_HOST=db
            - MYSQL_DB=octopus_db
        ports:
            - 5000:5000
        depends_on:
            - db
            - keystore
            - admin

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ./sql/up.sql:/docker-entrypoint-initdb.d/1.up.sql

    keystore:
        image: redis:alpine        

    admin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:mysql
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: password
        restart: always
        ports:
            - 8080:80